### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by tmbb** [OvermindDL1/ex_spirit#2]
These are things that came up in our private conversations which I think should be more explicit in the docs. Please feel free to correct me if any of these are wrong

* Explain why the ExDocs look "weird": the functions and macros are defined in the user module, so there aren't any @doc attributes to extract, and that's why the documentation is freeform, without the characteristic things like type signatures we're used to in other libraries.

* Related to the above, explain why the functions and macros are defined in the user module. It's done for speed, bug given the complications this brings, the trade-off should be explained. This is the topic of my third point.

* Explain the pitfalls of writing macros and possible solutions. Explain that a normal parser module should not usually define macros and should use `defrule` instead. In cases where macros are needed, they should be relegated to a macro module inside the user source, and `imported`/`required`/`use`d from there.

* Explain that long compile times (> 10.0s) are to be expected due to the extensive compile-time optimizations and that this isn't the user's fault.

**Comment by OvermindDL1** [comment]
> Explain why the ExDocs look "weird": the functions and macros are defined in the user module, so there aren't any @doc attributes to extract, and that's why the documentation is freeform, without the characteristic things like type signatures we're used to in other libraries.

Entirely true, this could be 'fixed' a couple of different ways:

* By putting the docs inside the macro and then using it into a manual-only 'module' for documentation
* By changing every-single-call to be entirely macro'd and carefully inlined to the resultant module, however this could be done in a backwards compatible way I'm quite sure.

> Related to the above, explain why the functions and macros are defined in the user module. It's done for speed, bug given the complications this brings, the trade-off should be explained. This is the topic of my third point.

It is indeed entirely for speed reasons.  Benchmarking with benchee showed a significant boost by inlining the functions into the user module for the function calls.

> Explain the pitfalls of writing macros and possible solutions. Explain that a normal parser module should not usually define macros and should use defrule instead. In cases where macros are needed, they should be relegated to a macro module inside the user source, and imported/required/used from there.

Hmm, yeah `defrule` should probably be made more prominent.  I made it powerful enough that every single existing rule in the system could be made using it (even though it was created 'after' most of them, perhaps it would be useful to dogfood it...)

> Explain that long compile times (> 10.0s) are to be expected due to the extensive compile-time optimizations and that this isn't the user's fault.

Lol, yeah this is the nature of significant macro's and inlining in exchange for speed.  With the current design it is not terribly fixable.

'However', I could go the 'Expression Template' style that the original Spirit uses (in C++).  It would be strictly more powerful, however it would require a much more so than *significant* redesign of everything and it would make the existing parsers into a near unreadable mess, however it would allow me to perform custom optimizations that macro's and the BEAM alone are not capable of doing, which would get a larger speed boost.  However although this may be faster to compile in some cases, it could also be slower to compile in others, however the extra optimizations could be disabled for dev time to exchange slower 'running' for faster compiling.  This is not an option that the current method has available.

**Comment by tmbb** [comment]
> this could be 'fixed' a couple of different ways:

I have another idea, that doesn't require changing anything in the way the macros are defined (I think). Just define new macros and functions inside the module (not under `__using__`) that raise with an error message (at runtime or compile time) and write the docs in those dummy functions or macros instead. Even better if there is a way of making the module impossible to import (something that would raise an error if the module were imported instead of used, which I don't think is possible). But just warning the user and raising on macro-expansion or function invocation is probably good enough.

**Comment by tmbb** [comment]
> Lol, yeah this is the nature of significant macro's and inlining in exchange for speed. With the current design it is not terribly fixable.

I was not complaining... Just saying you should warn the user. It surprised me a lot.

> 'However', I could go the 'Expression Template' style that the original Spirit uses (in C++)

From what I've read, this is basically the same as implementing a haskell compiler on top of the BEAM with stream fusion and other goodies. This seems very cool, but then dumb users like me will probably squander your performance gains by doing stupid stuff, so think about it before comitting to something like this.

**Comment by OvermindDL1** [comment]
> I have another idea, that doesn't require changing anything in the way the macros are defined (I think). Just define new macros and functions inside the module (not under __using__) that raise with an error message (at runtime or compile time) and write the docs in those dummy functions or macros instead. Even better if there is a way of making the module impossible to import (something that would raise an error if the module were imported instead of used, which I don't think is possible). But just warning the user and raising on macro-expansion or function invocation is probably good enough.

Hmm, that would work, bit of duplication of heads then and could be confusing though, but it could be put behind a 'dev/test' mix barrier so they don't even exist at prod/dependency time.  :-)

> From what I've read, this is basically the same as implementing a haskell compiler on top of the BEAM with stream fusion and other goodies. This seems very cool, but then dumb users like me will probably squander your performance gains by doing stupid stuff, so think about it before comitting to something like this.

Lol, that is the point of doing it that way, squander'ing performance gains could then be detected and either fixed or reported, the current method cannot.  ^.^

**Comment by tmbb** [comment]
The `Kernel.SpecialForms` module doesn't even bother hiding the function/macro heads - they just return an error. I see no reason why we couldn't do it ourselves. Look at the "definition" of unquote, for example:

```elixir
defmacro unquote(:{})(args), do: error!([args])
```

Where `error!` just raises an error at runtime.

**Comment by OvermindDL1** [comment]
Yep, the `Kernel.SpecialForms` modules is *purely* for documentation purposes, nothing more.  ^.^;

But yeah, could do the same.

**Comment by tmbb** [comment]
Done.
