### ISSUE TITLE
symbols() doesn't play well with lexeme()

### ISSUE THREAD

**Issue by tmbb** [OvermindDL1/ex_spirit#6]
```elixir
iex(15)> parse("x1", lexeme(symbols(TreeMap.new() |> TreeMap.add_text("x", "x"))))
%ExSpirit.Parser.Context{column: 3, error: nil, filename: "<unknown>", line: 1,
 position: 2, rest: "", result: "x1", rulestack: [], skipper: nil, state: %{},
 userdata: nil}
```

On the other hand, when used alone, `symbols()` causes no problems:

```elixir
iex(16)> parse("x1", symbols(TreeMap.new() |> TreeMap.add_text("x", "x")))
%ExSpirit.Parser.Context{column: 3, error: nil, filename: "<unknown>", line: 1,
 position: 2, rest: "1", result: "x", rulestack: [], skipper: nil, state: %{},
 userdata: nil}
```

If I had to guess, I'd say you've made a mistake while calculating the position of the new context returned by the symbol parser. This feature is kinda critical for having support for custom keywords in `makeup`.

**Comment by tmbb** [comment]
Fixed here: https://github.com/OvermindDL1/ex_spirit/pull/7

**Comment by OvermindDL1** [comment]
Ooooo, indeed I did make a bug in positioning!  Closing this as your PR does fix it!  ^.^
